config:
    default: true

    # Use ordered lists to make stuff easier to read in a text editor.
    ol-prefix:
        style: ordered

    # Use ATX-style headers (#) without closing pound sign.
    heading-style:
        style: atx

    # Not wrapping long lines makes diffs easier to read, especially for prose.
    # Instead, we should follow the "one sentence per line" pattern.
    line-length: false

    # Dollar signs are useful to indicate shell commands/type and help
    # distinguishing wrapped lines from new commands.
    commands-show-output: false

    # Indented code blocks are easier to read in a text editor, but don't allow
    # specifying a language for syntax highlighting. Therefore both indented and
    # fenced code block should be allowed depending on the use case.
    code-block-style: false

# Fix any fixable errors
fix: true
